"use client"

import React, { createContext, useEffect, useState } from 'react';
import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from "next-auth/react"
const inter = Inter({ subsets: ['latin'] })
import Navbar from './Navbar';
import Provider from './components/Provider'
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({children,}: {children: React.ReactNode}) {
  const [showNavBar, setShowNavbar] = useState(true)

  // useEffect(() => {
  //   setShowNavbar(true)
  // },[showNavBar])

  return (
    
    <html lang="en">
      <head>
        <script src='https://accounts.google.com/gsi/client' async defer></script>
      </head>
      
      <body className={inter.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
